# configure some default settings
[default]
confirmation_link_timeout = 12 # in hours
password_reset_timeout = 10 # in minutes
sqlalchemy_track_modifications = false
use_hugging_face = false

# configure the local environment settings, with a database on localhost
[local]
flask_debug = true
sqlalchemy_echo = false
db_host = "localhost"
db_port = "3306"
db_name = "coach"
db_user = "developer"
db_password = "123456"
sqlalchemy_record_queries = true
