# configure some default settings
[default]
confirmation_link_timeout = 12 # in hours
password_reset_timeout = 10 # in minutes
sqlalchemy_track_modifications = false
use_hugging_face = false

# configure the local environment settings, with a database on localhost
[local]
flask_debug = true
sqlalchemy_echo = false
db_host = "localhost"
db_port = "3306"
db_name = "coach"
db_user = "developer"
db_password = "123456"
sqlalchemy_record_queries = true

# configure the local environment settings, with a database on localhost
[local_Dimitar]
flask_debug = true
sqlalchemy_echo = false
db_host = "localhost"
db_port = "3306"
db_name = "coach"
db_user = "root"
db_password = "root"
sqlalchemy_record_queries = true

# configure the development environment settings, using a copy of the database
[development]
flask_debug = false
sqlalchemy_echo = false
db_host = "demo-db.c24rawpdnxrb.us-east-1.rds.amazonaws.com"
db_port = "3306"
db_name = "coach_dev"
db_user = "admin"
db_password = "database"
sqlalchemy_record_queries = false
use_hugging_face = true

# configure the production environment settings, with the production database
[production]
flask_debug = false
sqlalchemy_echo = false
db_host = "demo-db.c24rawpdnxrb.us-east-1.rds.amazonaws.com"
db_port = "3306"
db_name = "coach"
db_user = "admin"
db_password = "database"
sqlalchemy_record_queries = false
use_hugging_face = true


